backbee/backbee-js

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/main.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/ContentRevision.js
src/tb/apps/content/plugins/parameters/main.js
src/tb/config.js

On select a content a button "parameters" must be appear.
On click on this button a form must be build with a content definition provided by API.
Manage save with parameters.
For example:

#91 add parameters plugin

---

src/tb/core/ApplicationManager.js
src/tb/core/ControllerManager.js

I have apply that only on controller service because they are already async by creating a function beforeCall.
If the system is used, your service will get a require instance in first parameter.
to use the system you to add this config inner the controller :
```javascript
config: {
define: {
oneService: ['one/repository', 'dependency/you/need']
}
}
```

Add requirement system to load dependency upon request #136

---

src/tb/core/RestDriver.js

Add toString() method on the criteria to be sure the url segment get an String has parameter.

[RestDriver] request url construction with identifier has integer don't work #160

---

src/tb/component/exceptions-viewer/main.js
src/tb/component/exceptions-viewer/viewer.js
src/tb/config.js
src/tb/core/Api.js
src/tb/init.js

A little component to show the number of exception raised with Core.exception.
This coponent subscribe on the event 'api:set:lastError' and automaticly include a div into the document with the number of errors and on click on this div, we have console warn off each exceptions raised in the application.
For that, I add a mediator publish call into the api set function.
I know the fact of is disgusting to add style with the javascript, but we need to find a better way to include component css with out including it into bb-ui.less. 
And there is a little typo correction in component.js.

Create visual zone to show number of core.exception #182

---

src/tb/apps/content/plugins/contentsetplus/main.js

On init, the content is set to the object expect that the onInit is called one time.

#173 [Application] [Content] [Plugin] [contentsetplus] + the plugin is apply only for one content

---

src/tb/apps/content/plugins/contentselector/main.js

On get action, the creation command is in an object.
The createCommand function is used by this instead of self.

#198 [Content] [Plugins] [ContentSelector] Bad context for creation of the command

---

Gruntfile.js

Each time we want to execute tests, we have to execute all the test suite.
I suggest an easy way to filter the tests to be executed.
Usage:
```bash
➜  BbCoreJs git:(translator-component) grunt jasmine:coverage --path="component/translator/*.js"
Running "jasmine:coverage" (jasmine) task
Testing jasmine specs via PhantomJS
Translator core library test suite
✓ Should translate the key from default catalog
✓ Should set a new locale
=============================== Coverage summary ===============================
Statements   : 10.94% ( 320/2925 )
Branches     : 2.75% ( 33/1198 )
Functions    : 11.37% ( 96/844 )
Lines        : 10.94% ( 320/2925 )
================================================================================
2 specs in 2.394s.
>> 0 failures
Done, without errors.
```
What do …

Added  cli option in order to filter tests to execute

---

bower.json
specs/require.config.js
specs/tb/component/translator/Translator.spec.js
src/tb/component/translator/main.js
src/tb/config.js
src/tb/core/Renderer.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json
src/tb/init.js

Translator component is OK, I will improve it.
After thinking, I think the best place for this module is to be part of core *because* it will be mandatory.
In all cases, component or core, the translator works: I will add more tests and probably try to implement pluralization system.
When I tried to aggregate the translator into Renderer (and finaly, into nunjucks), this won't work.
I investigate a lot (and I will suggest a "Debug" component in the future because Javascript is damn so hard to debug!), and *in fact* the **Renderer don't work as expected**.
**update 20/02 17h49**: docs are to be done in another repo
**update 20/02 16h51**: the component work the way we expected :)

[RFR] Translator core library

---

specs/tb/core/Renderer.spec.js
src/tb/core/Renderer.js

This is a split of previous PR (https://github.com/backbee/BbCoreJs/pull/206) demonstrating that adding test to cover Renderer core library actualy *broke* the test suite.
This need more investigation, but as it's not related to the **Translator itself** I've done a new pull request.

[RFR] - Added Renderer tests

---

src/tb/apps/content/components/MouseEventManager.js

The jQuery object is not present in the DOM when instanciation of content is done.

#224 Unclickable content after use contentsetplus or contentselector plugin

---

src/tb/apps/content/components/PluginManager.js

Currently, the onInit function is in the handleLoading function.
The handleLoading function is called one time and call the onInit function if is valid in the scope and in the context.

#222 [Content] [PluginManager] + onInit function not called all the time

---

src/tb/apps/bundle/templates/list.twig

In order to help the user find a bundle, show him how bundles are organized (accordeons)

[Bundle] #115 The first category of bundle in the drop list should be visible

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/views/bundle.view.index.js

Better add a popin to confirm the activation/desactivation of a bundle
Activating desactivating a bundle can be a key issue, in case of missclick it is important to have this security.

[Bundle] #114 Add a popin to confirm the activation/desactivation of a bundle

---

specs/tb/core/Utils.spec.js
src/tb/apps/user/controllers/group.controller.js
src/tb/apps/user/controllers/user.controller.js
src/tb/core/Utils.js

I create this PR, because currently I have a problem with the response type in getCollectionAction from the User Rest Controller. This evol permit to avoid bad typing response from the server and help the JS to continuing working correctly.
I add a new function into Utils class castAsArray to transform an object into an array.
And I use that function into group and user controller to avoid the badly response type from the BackBee REST server.

Forcing get pagination response to be an array

---

specs/tb/core/Mediator.spec.js
src/tb/core/Mediator.js

I have rewrite the mediator exception to ease debugging.
* The message is more short
* Add params exception where you can find now : topic, context, callback and arguments
I have update the exception test.
[bonus] I add one more test for a case was not already tested (Subscribe with no context them publish) that check the fact of the context is undefined by default.

[mediator] improvement of the mediator exceptions

---

specs/tb/core/Mediator.spec.js
src/tb/core/Mediator.js

A little addition of a forgotten parameter during the Mediator exception enhancement.

Add error caught in the mediator exception

---

src/tb/core/ApplicationManager.js
src/tb/core/Scope.js
src/tb/main.js

This update, allow applications to expose service outer the main app in a scope.
config example
```yaml
user:
scope:
global:
open: controllername.servicename
close: controllername.otherservicename
```
parameters open and close are optional.
I took the opportunity to clean a little ApplicationManager by removing console.log and renaming the variable with the standards name.

Add services autobinding on scopes

---

composer.json

Hi, @ndufreche and @mickaelandrieu 
ToolbarBundle refers to this as backbee/client-js but it's real name is BbCoreJs.
What do you think about backbee/bb-core-js as the package name, seams to be more standard ?

#306 Add composer.json file

---

src/tb/component/popin/main.js

Currently, if the content is set after the popin is shown, the content is not shown.

[Component] [Popin] + fix to set content after the popin is displayed

---

less/fix.less

Related to this issue: https://github.com/backbee/backbee-standard/issues/114
When you move to a top content, sometimes the top buttons are not displayed: they are hidden behind the BB toolbar.
The new behavior:

Fixed block top buttons displaying

---

src/tb/apps/page/templates/contribution.index.twig

Just button deletion in the page template because the functionality is not created in core php. #399

removing create draft page

---

src/tb/apps/page/widgets/InformationPage.js

Page status popin is attach to bottom right and stay at this place on navigator re-size.

attach page status popin at bottom right

---

src/tb/apps/content/widgets/Breadcrumb.js

Just a little placeholder in case the property name is not available (case met was with content set)

Add placeholder content has no property name

---

src/tb/apps/page/controllers/main.controller.js

This enforces the redirection to the newly duplicated page. (refs: https://github.com/backbee/backbee-standard/issues/113)

Fixed redirection on page duplication

---

src/tb/apps/content/views/content.view.contribution.index.js

This remove the weird limit that "actualy" hide the fact that the carousel is not integrated.

#427 - Fix blocks displaying

---

src/tb/component/session/session.js

See #556 , changed "Bad credentials" to "login or password incorrect".
Notice: we don't have any access to the translator component atm.

Fixed #556 - Change bad credentials label

---

src/tb/apps/page/views/page.view.tree.contribution.js

On page tree view, the "Remove" option didn't redirect the user.
So, a deleted page seems to be already there, until you reload by yourself (and catch a Not found), now the behavior is the good one.

Fixed #615 - redirection after page deletion on page tree plugin

---

src/tb/apps/page/views/page.view.contribution.index.js
src/tb/component/revisionselector/main.js

https://github.com/backbee/BbCoreJs/issues/605

REFS #605 - cancel/validate/draft popins are now center top displayed

---

src/tb/init.js

If the PHP session is expired, the js session is always in local storage.

Fix reconnect after session expired

---

src/tb/component/contentselector/helper/content.renderer.js

A contentselector can't be open cause that require a bad file.

[Component] [Contentselector] Remove non exist require content.grid.view.tpl

---

src/tb/apps/content/components/DefinitionManager.js

Last update of Google Chrome ``43.0.2357.65 m`` does not allow anymore this syntax:
```js
img = document.createElement('img');
img.style = {
width: '25px',
height: '25px'
};
```
Instead of this use this:
```js
img = document.createElement('img');
img.style.cssText = 'width: 25px, height: 25px';
```
Btw this is the right expected syntax.

Fixed DefinitionManager::addDefinition to use right syntax of document element style property

---

src/tb/apps/user/controllers/user.controller.js

This fix issue backbee/backbee-standard#298 (the logout on subpages doesn't work as expected).
The fix allow subpages to update cookie form domains.
ping @ndufreche

The cookie is now available from subpages

---

src/tb/apps/page/forms/AbstractPage.form.js

this fix this issue => https://github.com/backbee/backbee-standard/issues/359

REFS #359 - Remove "_top" and "_parent" option to new page creation

---

src/tb/apps/page/components/SaveManager.js

Note this patch don't fix the translation issue on Online/Offline.

use parseInt because string is received

---

src/tb/apps/content/widgets/Edition.js

If the content don't have elements a call for fetch all content are called

Fix preload on content edit if empty elements

---

src/tb/apps/content/controllers/main.controller.js

Currently if an element is null an error is throw and prevent edit

Fix edit content when element is null

---

src/tb/apps/content/components/ContentManager.js

I add a test for src var in contentmanager.js
if src is undefined, contentmanager put defaultPicturePath instead throw an error.

add test for undefined var

---

src/tb/apps/content/repository/revision.repository.js

After some tests, the user is waiting far more time the validation of his drafts when API calls are highly split.
On my not so powerful pc, 23 contents validated 3 by 3 reach the php timeout limit for half of the 8 calls.
Pushing the limit to 30 (so only one API call) it's ok!
I propose to set the limit to 30 and to plan a perf. study on several limit value.

Pushing the commits limit sent at the same time to 30

---

src/tb/component/formsubmitter/elements/contentTypeSelector.js

Currently an error is thrown when value is empty

Fix JSON.parse on empty string

---

src/tb/component/linkselector/main.js

In order to be able to contribute various type of url in external links selector (http(s), mailto, with get parameters ? or anchor #, etc...), removed the validation regex and test (Charles suggestion).

Removed external link selector regex validation

---

src/tb/component/contentselector/helper/content.renderer.js

As per discussed with @clementbonfils 
The change is made for all content types, not only for Articles.
The pop in has a minWidth = 450 and minHeight = 200 and maxWidth and maxHeight were removed.

[CONTENT SELECTOR] Enable to resize the see pop in

---

src/tb/apps/content/plugins/contentsplitter/main.js

Currently if parent is a page ContentSet, that throw exception

Fix contentsplitter when parent is a BackBee ContentSet

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/apps/page/views/page.view.tree.js

Changes for the following requests:
2. Pages that have subpages must be displayed before single pages
3. When creating a new page, display the page right after it parent . when reloading tree, page must go down after pages that have children
4. As soon as the toobar is loaded , load the tree in background task (for user to have it display quick when he'll click on it)(edited)

Tree adjustments refs:#5362

---

src/tb/apps/content/plugins/contentsplitter/main.js

The contentspliter section in plugins.yml has to be modified as follows :
contentsplitter:
accept: ['*']
config:
splittableContents:
- Text/Paragraph
- Text/Example
- Text/AnOtherExample

enable config in contentsplitter plugin

---

src/tb/apps/contribution/views/contribution.view.index.js

In some cases (like going to page management) the tree popin was destroyed and wasn't found in the page anymore. I fixed it by re-initializing it.
Issue related: https://github.com/backbee/backbee-standard/issues/573

Tree popin reinit after destroy #573

---

src/tb/component/formbuilder/form/views/form.view.js

If the multiple selectors have at least one option selected and then you want to have no option selected, this was not saved, it kept the previous values.

Multiple selectors issue refs:#5860

---

src/tb/apps/content/views/content.view.contribution.index.js

Fix for https://github.com/backbee/backbee-standard/issues/683
After destroy the popin couldn't open anymore.

#683 fix block display cant be opened twice

---

src/tb/apps/content/models/AbstractContent.js

The "default" render mode was "hard forced" in code.
This prevented the selection of a proper default render mode in a ClassContent yml configuration.
This fix is linked to ToolbarBundle #102 (https://github.com/backbee/ToolbarBundle/pull/102).
Please merge both at the same time.
Thanks

fix default render mode for ClassContent

---

src/tb/apps/user/controllers/group.controller.js

When the users list is very long, the group list gets distorted until the user ajax finishes.

Resize zones usergroup refs:#8119

---

src/tb/apps/bundle/templates/admin.twig

The bundle admin layout was not full-width. The column width is now 100%.
Thanks.

fix bundle admin template full width

---

src/tb/component/formbuilder/form/element/views/form.element.view.file.js

The anonymous creation caused 401 forbidden access on secured instances.

Remove anonymous thumbnail creation from dropzone
