src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/main.js

The event "on:save:click" must be dispatched into contribution application.
All application who need to save something must subscribe to this event.

#85 dispatch event when click on save

---

src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/main.js

Revert "#85 dispatch event when click on save"

---

src/tb/apps/main/controllers/main.controller.js

Error throwed if onInit is not implemented

#98 Add onInit function on mainController of application main

---

src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/Content.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/repository/content.repository.js

We need a little refactoring of content cause the object have so much attributes.
Fix application which use content object

#100 Refactoring of content

---

html/css/fix.css
src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/components/PluginManager.js
src/tb/apps/content/main.js
src/tb/apps/content/plugins/contentplugin.js
src/tb/apps/content/plugins/contenttype.plugin.js
src/tb/apps/content/plugins/edit.plugin.js
src/tb/apps/content/templates/content-action.twig
src/tb/config.js

Allow plugins to add actions above contents.

#104 new content plugin Manager

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/repository/content.repository.js

Actually the addition of one block is too bound to dnd.

#102 Change the addition of a block to another

---

src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/Content.js
src/tb/apps/content/models/ContentRevision.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/main/main.js

Subscribe to the event "on:save:click" and do treatment for save all content added and updated.

#86 Manage save on content application

---

specs/tb/component/authentication/Authentication.spec.js
src/tb/component/authentication/main.js
src/tb/core/RequestHandler.js
src/tb/init.js
src/tb/main.js

AuthenticationHandler is too specialized to be in core.

#24 remove AuthenticationHandler from core

---

src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/controllers/main.controller.js

On contribution application it will be fine to dispatch a event when a cancel button is clicked.

#121 [Contribution] Dispatch cancel event

---

src/tb/apps/content/main.js
src/tb/apps/content/plugins/contentsetplus/main.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/content/templates/palette-blocks.twig
src/tb/apps/content/widgets/DialogContentsList.js
src/tb/config.js

This plugin add content directly in the contentset.
When contentset don't have accept, i will show a popin for choose a content.

#126 [Contribution] [Content] [Plugin] + add plugin '+' on contentset

---

Gruntfile.js
less/bb-ui-login.less
less/bb-ui.less
less/bb-var.less

- debug less files
- remove bb-var.less from the Gruntfile file less:css task; 
- rename bb5-*.less -> bb-*.less

re order variables declaration #132

---

src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/plugins/remove/main.js
src/tb/config.js

On click, the current content is remove.

#131 [Contribution] [Content] [Plugin] + add plugin remove

---

src/tb/apps/content/views/content.view.contribution.index.js

Actually, the contribution use a custom listing of block, i create a widget for this and must be implemented in this.

#129 Use a widget DialogContentsList for listing block in contribution content

---

src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/plugins/parameters/main.js

A parameters must not be saved if new parameters is equal than old.
A Request API for retrieve parameters is changed.

#138 [Contribution] [Content] [Plugin] fix parameters

---

src/tb/apps/page/controllers/main.controller.js
src/tb/component/formbuilder/form/element/NodeSelector.js
src/tb/component/formbuilder/form/element/templates/nodeSelector.twig
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js

This element allow to choose a page of site into a tree.

#68 Create node selector element in formbuilder

---

src/tb/core/Exception.js

For ease the debugging, we need to have the possibility transfer the function parameters to the exception.

[Exception] add the possibility to add params when exception is raised #144

---

src/tb/core/Renderer.js

add try catch inner render function.

[renderer] catch rendering exception #146

---

src/tb/apps/page/main.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/widgets/InformationPage.js
src/tb/apps/page/widgets/templates/information-page.twig

Show popin with different data like state of page, modifed date etc..

#148 Add popin state of current page

---

src/tb/component/formbuilder/form/element/templates/text.twig

Add the placeholder option echo into text.twig

[formbuilder] add placeholder into text #151

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/repository/bundle.repository.js
src/tb/apps/bundle/templates/index.twig
src/tb/apps/bundle/views/bundle.view.index.js
src/tb/apps/bundle/views/bundle.view.list.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/templates/contribution.index.twig
src/tb/apps/content/views/content.view.contribution.index.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/components/ToolbarManager.js
src/tb/apps/main/components/templates/tab-wrapper.twig
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/main.js
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/views/page.view.clone.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.delete.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js

Optimize load of all applications

#150 Optimize navigation in toolbar

---

less/component-notify.less
less/fix.less
src/tb/apps/main/templates/toolbar.twig
src/tb/component/notify/main.js

Recovery the old notification system from 0.11 js version.

[component] create user notification system #155

---

html/demo-build.html
html/demo.html
html/dnd.html
html/mainApp.html
specs/tb/core/Scope.spec.js
src/tb/apps/bundle/templates/index.twig
src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/plugins/edit/main.js
src/tb/apps/content/templates/contribution.index.twig
src/tb/apps/contribution/templates/index.twig
src/tb/apps/main/templates/toolbar.twig
src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/templates/manage.list.twig
src/tb/apps/page/views/page.view.delete.js
src/tb/component/contentselector/templates/content.delete.tpl
src/tb/component/contentselector/templates/content.grid.view.tpl
src/tb/component/contentselector/templates/content.list.view.tpl
src/tb/component/contentselector/templates/layout.tpl
src/tb/component/contentselector/templates/pager.tpl
src/tb/component/popin/main.js
src/tb/config.js
src/tb/core/ApplicationManager.js
src/tb/core/Scope.js

Some labels need to be updated and translated.
I also fixed some typos.
I think a lot of french contents are from ``backbee/BackBee`` so I will check also the core php project.
Please review :)

Fixed all french contents and some typos

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/content/repository/revision.repository.js
src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/main.js
src/tb/component/revisionselector/main.js
src/tb/component/revisionselector/managers/Draft.js
src/tb/component/revisionselector/managers/Event.js
src/tb/component/revisionselector/managers/Save.js
src/tb/component/revisionselector/templates/item-wrapper.twig
src/tb/component/revisionselector/templates/tree.twig
src/tb/config.js

- Create a popin which lists all revision was saved . It allows you to make the choice about save.
- Add validate management

#154 Create revision component

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/main/main.js
src/tb/component/revisionselector/main.js
src/tb/component/revisionselector/templates/tree.twig

Use revision selector for revert content.

#166 Add revert management

---

src/tb/apps/contribution/templates/index.twig

Issue reference:
https://github.com/backbee/backbee-standard/issues/73

#73 - "valider" is still in french

---

src/require.config.js
src/tb/apps/bundle/repository/bundle.repository.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/content/repository/revision.repository.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/user/repository/abstract.rest.repository.js
src/tb/component/authentication/main.js
src/tb/component/datastore/DataStore.js
src/tb/init.js

...js load
[Init] #174 - Set the base URL for RestDriver with data-api attribute value + Load app on data-autostart attribute setting
[RestDriver] #174 - Removing specific call to RestDriver.setBaseUrl() by apps and components
[User] #174 - Removing call to RestDriver.setBaseUrl()

[Require.Config] #174 - Review calls to REST API

---

src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/plugins/edition/ElementInterpreter.js
src/tb/apps/content/plugins/edition/elements/All.js
src/tb/apps/content/plugins/edition/elements/ContentSet.js
src/tb/apps/content/plugins/edition/elements/Text.js
src/tb/apps/content/plugins/edition/main.js
src/tb/apps/content/repository/content.repository.js
src/tb/component/formbuilder/form/element/Content.js
src/tb/component/formbuilder/form/element/ContentSet.js
src/tb/component/formbuilder/form/element/templates/content.twig
src/tb/component/formbuilder/form/element/templates/contentSet.twig
src/tb/component/formbuilder/form/element/templates/contentSet_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.content.js
src/tb/component/formbuilder/form/element/views/form.element.view.contentSet.js
src/tb/component/formbuilder/form/views/form.view.js
src/tb/component/rangeselector/main.js
src/tb/config.js

Show elements of content with a form associated.
For the moment, i have create edition of content value and contentSet.
Remains to be done:
- Image
- Keywords
- Link

#168 [Content] [Plugin] Create edition plugin

---

src/tb/apps/content/plugins/contentselector/main.js

Remove console log which do an error

#189 [Content] [Plugins] [ContentSelector] Remove error from console log

---

src/tb/core/Exception.js

I have change the parsing system with a regex.

[exception] debug stack line parsing #191

---

src/tb/core/Exception.js

Reverts backbee/BbCoreJs#192
Because the regex is too restrictive

Revert "[exception] debug stack line parsing #191"

---

src/tb/apps/content/plugins/edition/main.js

Do not use this plugin for contentset

#203 [Content] [Plugins] [Edition] Not use for contentset

---

src/tb/apps/content/plugins/contentsetplus/main.js

Cause of old commit which delete this.content attribution from onInit and don't change in other function.

#200 [Content] [Plugins] [ContentSetPlus] doesn't work

---

less/fix.less
src/tb/apps/content/plugins/contentsetplus/main.js
src/tb/apps/content/plugins/edition/main.js
src/tb/apps/content/plugins/parameters/main.js
src/tb/config.js

- Add plugins to all content
- Change icon for plugins
- Fix css of plugins button
Don't forget to use grunt less:css

#194 Update use of plugins

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/config.js

Add to the config.js an list of element non clickable

#205 [Content] Don't be able to click on native element

---

src/tb/apps/content/plugins/parameters/main.js

Show params only with a valid attributes (min: type).

#218 [Content] [Plugins] [Parameters] + Verify mandatories attributes for parameters

---

src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/controllers/main.controller.js

Cause bad context used and bad var used in getEditableContentService from content application

#216 [Component] [RTE] + fix elements not found

---

src/tb/component/formbuilder/form/element/templates/password.twig

MIssing display error on element password

[FormBuilder] #3 add error on element password

---

specs/tb/core/Api.spec.js
src/tb/core/Api.js

I add 100% code coverage on tb.core.Api
On the object have done a little optimization in register function and debug unset function.

[test] Add tb.core.Api test and add some optim

---

less/fix.less
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/main.js
src/tb/apps/content/templates/breadcrumb.twig
src/tb/apps/content/widgets/Breadcrumb.js
src/tb/apps/main/templates/toolbar.twig

[Content] #34 Add Breadcrumb for content

---

specs/tb/component/translator/Translator.spec.js
src/tb/apps/contribution/templates/index.twig
src/tb/component/translator/main.js
src/tb/core/Renderer.js
src/tb/init.js

#240 Translator should be used inside applications

---

src/tb/apps/bundle/views/bundle.view.list.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/main/main.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/main.js
src/tb/component/formbuilder/form/element/views/form.element.view.content.js
src/tb/component/formbuilder/form/element/views/form.element.view.contentSet.js
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js
src/tb/component/formbuilder/form/views/form.view.js
src/tb/component/popin/main.js
src/tb/component/treeview/PopinTreeView.js

Change #bb5-ui to use a Core.config

#235 Use a global variable instead of a same variable in each file

---

src/tb/apps/bundle/main.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/contribution/main.js

#170 adding scopes to content application

---

src/require.config.js
src/tb/apps/user/controllers/group.controller.js
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/entity/user.js
src/tb/apps/user/templates/group/delete.twig
src/tb/apps/user/templates/group/list.item.twig
src/tb/apps/user/templates/group/list.twig
src/tb/apps/user/templates/popin.twig
src/tb/apps/user/templates/toolbar.twig
src/tb/apps/user/templates/user/delete.twig
src/tb/apps/user/templates/user/list.item.twig
src/tb/apps/user/views/group/view.list.js
src/tb/apps/user/views/popin.view.js
src/tb/apps/user/views/user/view.list.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

[wip][user] Add user/group integration #245

---

less/fix.less

Fix visibility of errors in form

---

src/tb/apps/bundle/views/bundle.view.list.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/main/main.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/main.js
src/tb/component/formbuilder/form/element/views/form.element.view.content.js
src/tb/component/formbuilder/form/element/views/form.element.view.contentSet.js
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js
src/tb/component/formbuilder/form/views/form.view.js
src/tb/component/popin/main.js
src/tb/component/treeview/PopinTreeView.js
src/tb/init.js

#260 Connexion doesn't work correctly

---

less/fix.less
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/linkselector/main.js
src/tb/component/linkselector/templates/layout.twig
src/tb/component/linkselector/templates/page-item.twig
src/tb/component/pagination/main.js
src/tb/component/popin/main.js
src/tb/i18n/en_US/global.json

#89 Create a link selector component

---

src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/entity/user.js
src/tb/apps/user/form/edit.user.form.js
src/tb/apps/user/form/new.user.form.js
src/tb/apps/user/views/user/form.view.js

This PR is to fix the javascript issue, exposed into #181

User edition fixes #181

---

src/tb/component/formbuilder/form/element/Element.js

The element of a form accept now an error parameter

Ease the adding form exception

---

src/tb/apps/main/templates/toolbar.twig
src/tb/apps/main/views/main.view.index.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

[RFR] Added translations for toolbar (main) app

---

specs/tb/core/RestDriver.spec.js
src/tb/core/RestDriver.js

Little update on REST driver to add the accept parameter in HTTP header.

[rest] the rest client have to specified the accept parameter. #273

---

src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/templates/manage.list.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

[RFR] Added translations for Page application

---

bower.json
src/require.config.js
src/tb/component/formbuilder/form/Form.js
src/tb/component/formbuilder/form/element/File.js
src/tb/component/formbuilder/form/element/templates/file.twig
src/tb/component/formbuilder/form/element/views/form.element.view.file.js
src/tb/component/formbuilder/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json
src/tb/init.js

- Add file with drag and drop or click for search in library
- Import of dropzone library
- Publish event in formbuilder when form is rendered

[Component] [Formbuilder] + add file element

---

src/tb/apps/contribution/templates/index.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

See #266 -> app -> contribution

[RFR] Added translations for Contribution application

---

src/tb/apps/bundle/templates/index.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

[RFR] Added translations for bundle apps

---

src/tb/component/formbuilder/form/element/templates/contentSet.twig
src/tb/component/formbuilder/form/element/templates/contentSet_item.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

- Change button style
- Change list style

[Component] [Formbuilder] + fix integration of contentset element

---

src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/treeview/PopinTreeView.js
src/tb/component/treeview/main.js
src/tb/component/treeview/templates/popin.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

- Fix manage of limit for get the next result
- Delete a "next result" button after load the page
- Change the tree action to a service
- update TreeView (Export html to a file and add event for the action of tree)

[Contribution] + fix tree

---

less/bb-ui.less
src/tb/apps/content/templates/contribution.index.twig
src/tb/apps/page/templates/contribution.index.twig

- fix align of displays checkbox

Fix css of displays link in contribution

---

src/tb/apps/user/templates/toolbar.twig

- Fix integration of user toolbar

[User] + fix toolbar integration

---

less/bb-ui.less
less/fix.less

[Content] + fix css for dropzone

---

src/tb/apps/content/main.js
src/tb/apps/content/plugins/edition/main.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/ElementInterpreter.js
src/tb/component/contentformbuilder/elements/Image.js
src/tb/component/formbuilder/form/element/templates/file.twig
src/tb/component/formbuilder/form/element/views/form.element.view.file.js

You can now use the Edition widget like:
```
require('content.widget.Edition').show(content);
```
That will show in the popin a form with validation and submit treatment.

Add widget for show a form of a element's content

---

less/bb-ui.less

Initialize a height of toolbar

fix height of toolbar

---

src/tb/component/popin/main.js

The loader picture is too close of a message annd color is not correct

[Component] [Popin] + fix css of loader

---

less/bb-ui.less

Fix css of the context menu

---

less/bb-ui.less

When the popin is shown, she create a lot of spaces in the page.

Fix shown of popin

---

src/tb/apps/content/models/ContentSet.js

Currently when an element is add in the contentset, the rendermode is not used

[Content] use the correct rendermode when add element in contentset

---

less/fix.less
src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/dnd/CommonDnD.js
src/tb/apps/content/components/dnd/ContentDrag.js
src/tb/apps/content/components/dnd/ContentDrop.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/plugins/dnd/main.js
src/tb/apps/content/templates/dropzone.twig
src/tb/component/dnd/main.js

- Use dnd as plugin
- Rework and split a dnd management

Fix drag and drop

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/plugins/remove/main.js
src/tb/apps/content/widgets/Breadcrumb.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

- Add confirmation for delete a content
- Move a BreadCrumb into a abstractContent
ref #248

[Content] [Plugins] [Remove] #248 Add confirmation when delete a content

---

src/tb/apps/main/templates/toolbar.twig
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/form/current.user.form.js
src/tb/apps/user/form/password.user.form.js
src/tb/apps/user/templates/user/toolbar.twig
src/tb/apps/user/views/user/current.form.view.js
src/tb/apps/user/views/user/toolbar.js
src/tb/core/ControllerManager.js

I have add a new exception for ease the debug of dependencies loading.

Add user personnal account management #164

---

src/tb/apps/user/controllers/dnd.controller.js
src/tb/apps/user/controllers/group.controller.js
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/form/edit.user.form.js
src/tb/apps/user/main.js
src/tb/apps/user/repository/abstract.rest.repository.js
src/tb/apps/user/templates/user/list.item.twig
src/tb/apps/user/views/popin.view.js
src/tb/apps/user/views/user/view.list.js
src/tb/component/translator/main.js
src/tb/core/ApplicationManager.js

Lot of debugging of user application 
issue fixed into this PR
- #180 
- #178
- #179 
I have added to a shortcut into the core api to get trans method and add an exception to catch the error during service execution.

User app debug

---

less/bb-ui.less

Too many spaces into the menu of toolbar

fix the height of main menu in toolbar

---

less/bb-ui.less
src/tb/component/formbuilder/form/element/templates/checkbox.twig
src/tb/component/formbuilder/form/element/templates/content.twig
src/tb/component/formbuilder/form/element/templates/contentSet.twig
src/tb/component/formbuilder/form/element/templates/datetimepicker.twig
src/tb/component/formbuilder/form/element/templates/file.twig
src/tb/component/formbuilder/form/element/templates/nodeSelector.twig
src/tb/component/formbuilder/form/element/templates/password.twig
src/tb/component/formbuilder/form/element/templates/radio.twig
src/tb/component/formbuilder/form/element/templates/select.twig
src/tb/component/formbuilder/form/element/templates/text.twig
src/tb/component/formbuilder/form/element/templates/textarea.twig

- fix integration of all elements

[Component] [Formbuilder] + fix integration of elements

---

specs/tb/component/authentication/Authentication.spec.js
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/templates/user/toolbar.twig
src/tb/component/authentication/main.js
src/tb/component/session/authenticate.js
src/tb/component/session/main.js
src/tb/component/session/session.js
src/tb/init.js

A little refactoring of the authentication component to  optimize the require loading.
I have create a new component session to manage the user session, this component is dependent with the authentication component.
If the session is not authenticate, it do a require of the authentication component.
I have add logout service into the user application to.

Updating authentication, optimizing require loading and add logout action

---

specs/tb/core/DriverHandler.spec.js
specs/tb/core/Request.spec.js
specs/tb/core/Response.spec.js
specs/tb/core/RestDriver.spec.js
src/tb/core/DriverHandler.js
src/tb/core/Request.js
src/tb/core/RequestHandler.js
src/tb/core/Response.js
src/tb/core/RestDriver.js

Remove all the datas and criterias typo in functions, commentaries and specs.
issue #310

remove typos into RestDriver, Request, Response an DriverHandler

---

src/tb/apps/content/controllers/main.controller.js

little debug in content man controller to enabled content dnd

[contribution][dnd] debug main controller

---

src/tb/apps/user/views/group/delete.view.js
src/tb/apps/user/views/popin.view.js
src/tb/apps/user/views/user/current.form.view.js
src/tb/apps/user/views/user/delete.view.js
src/tb/apps/user/views/user/form.view.js

This little tricks permit to remove some bugs in the user application identified by @clementbonfils in issue #303

[user] Add close function with popin destruction

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/controllers/main.controller.js

Before new page creation the user is redirected to this new page.
I add this behavior only on the button in contribution tab.
issue #246

[page] redirect on the new page before creation #246

---

src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/form/edit.user.form.js
src/tb/apps/user/repository/abstract.rest.repository.js
src/tb/apps/user/templates/toolbar.twig
src/tb/apps/user/views/toolbar.view.js

Creation of the search form with name, email, login and status input.
Removing the login input from edit user form.
And remove one console log forgotten in other commit.

[user] Search form creation

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/routes.js
src/tb/apps/bundle/templates/index.twig
src/tb/apps/bundle/views/bundle.view.index.js

[bundle] On click "my extentions" button will toggle bundle list

---

src/tb/apps/user/views/popin.view.js

This is a proposal for issue #178 
The user popin is now not closable, do 100% in width, is placed under the toolbar and take 100% of the height.

user popin fixes

---

src/tb/component/popin/PopIn.js
src/tb/component/popin/main.js

moveOnTop method added. Hide method is called when the dialog is closed

#319 moveOnTop method added. Hide method is called when the dialog is closed

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/dnd/ContentDrop.js
src/tb/apps/content/main.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/repository/resource.repository.js

[Content] + add dnd from for picture

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/dnd/ContentDrop.js

We don't know if the drag is a picture, i verify with the files length into a datatransfer

[Content] + fix drag and drop cause of do drop media function

---

src/tb/apps/content/widgets/Edition.js
src/tb/component/dataview/main.js
src/tb/component/medialibrary/helpers/mediaitemrenderer.helper.js
src/tb/component/medialibrary/main.js
src/tb/component/popin/PopIn.js
src/tb/component/popin/main.js

And some fixes in Popin component.

Medialibrary pick and dialog fixes

---

src/tb/component/component.js

Just a little fix for the error:
http://backbee-standard.dev/resources/toolbar/tb.core.Api.js?cb=0.8592774658463895 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Component loading fail firefox debug

---

src/tb/apps/content/components/DefinitionManager.js
src/tb/apps/content/components/dnd/ContentDrag.js

- Currently the first drag an drop of block doesn't work.

[Content] fix the first dnd of block

---

less/fix.less
src/tb/component/popin/main.js

Add scroll when the popin is too large or long.

Add scroll on popin

---

src/tb/component/revisionselector/managers/Draft.js
src/tb/component/revisionselector/managers/Event.js

Scalar's element is not displayed currently

[RevisionSelector] + fix elements has scalar

---

src/tb/apps/content/components/ContentContainer.js
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/DndManager.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/main/main.js

Currently, if the contentset don't have elements we can't see correctly where is a zone.

[Content] + add default zone if contentset don't have elements

---

src/tb/apps/user/templates/toolbar.twig

Organize columns and form in toolbar.twig

[User] + organize columns and form in toolbar.twig

---

src/tb/apps/content/plugins/contentsetplus/main.js

Use the same variable for a different treatment

[Content] [Plugin] [Contentsetplus] + fix add content when the contentset accept one type of content

---

src/tb/apps/content/plugins/contentsetplus/main.js

Fix the duplication of content

[Content] [Plugin] [Contentsetplus] + fix duplication of content

---

less/bb-ui.less
src/tb/apps/user/controllers/group.controller.js

[User] + change css for user list in modal

---

src/tb/apps/content/plugins/parameters/main.js
src/tb/apps/content/widgets/Edition.js

After edition of elements, other content are not unselectionnable

[Content] + fix selection after edition of elements

---

src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/views/page.view.manage.js

Little debug to able the popin displaying.

debug popin application

---

src/tb/apps/main/views/main.view.index.js

removing parameters and page tab

removing unused or unfinished tabs

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/main.js
src/tb/apps/page/controllers/main.controller.js

The current url is saved in local storage.
Waiting new dist version of core-js for merge.

Keep the current tab after reloading page

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/templates/toolbar.twig
src/tb/apps/user/controllers/main.controller.js
src/tb/i18n/en_US/global.json

Creating a method to set the title pane

---

src/tb/component/revisionselector/managers/Event.js
src/tb/component/revisionselector/templates/item-wrapper.twig
src/tb/component/revisionselector/templates/tree.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

- Add checkbox for select / unselect all items

[Component] [RevisionSelector] + add all select management

---

dist/css/bb-ui.css
less/bb-ui.less

increase space between users groups and fix height to prevent bad return to the line

[USER] increase space and fix height

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/contribution/main.js
src/tb/apps/main/main.js

Move scope event of content to the main application

Move scope event of content to the main application

---

src/tb/apps/user/controllers/dnd.controller.js

Drop user in a group #302 
This PR doesn't resolve totally the issue, some CSS adjustment is necessary to.

add ui-state-hover class during dnd over

---

src/tb/apps/content/components/PluginManager.js

Currently, the onEnable callback is called even if it's the same content.

[Content] Fix enabling plugin when click on the same content

---

src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/component/medialibrary/main.js
src/tb/component/treeview/NodeEditor.js
src/tb/component/treeview/TreeView.js
src/tb/i18n/en_US/global.json

Enabling medialibrary folder edition.

fixing medialibrary editing bug

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/templates/palette-blocks.twig
src/tb/apps/content/widgets/DialogContentsList.js

this is an amazing description very useful to help someone actualy review my wonderful pull request

Add drag and drop on palette block

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/i18n/en_US/global.json

for "contribution" => Edit page
for "extensions" => Manage bundles

[Refs #358] Update tab titles

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/main.js
src/tb/apps/bundle/templates/confirm.twig
src/tb/apps/bundle/views/bundle.view.index.js
src/tb/apps/bundle/views/confirm.view.js
src/tb/i18n/en_US/global.json

bug fix for issue
Remove confirm popout and add popin with translation in bundle index view #318

REFS #318 - removed confirm popout and add popin in bundle index view

---

src/tb/apps/contribution/controllers/main.controller.js
src/tb/component/medialibrary/main.js
src/tb/component/treeview/NodeEditor.js

Create one instance of the MediaLibrary when we click many times on the media Library button.

fixing loading bug for MediaLibrary

---

src/tb/component/formbuilder/form/templates/form.twig

The display of a group with several elements was not good

[Component] [FormBuilder] + Fix render of element with group

---

src/tb/apps/content/widgets/DialogContentsList.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Change "Block list" to "Categories of blocks"

[Content] Change title of block list

---

src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/components/PluginManager.js
src/tb/apps/content/plugins/parameters/main.js
src/tb/component/formbuilder/form/element/MediaSelector.js
src/tb/component/formbuilder/form/element/templates/mediaSelector.twig
src/tb/component/formbuilder/form/element/templates/mediaSelector_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.mediaSelector.js
src/tb/component/formsubmitter/elements/mediaSelector.js
src/tb/component/medialibrary/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

mediaSelector is a new element of formbuilder, he can add one or several medias.

[Component] [FormBuilder] + add media element

---

src/tb/component/treeview/PopinTreeView.js

[Component] [Treeview] + fix tree position

---

dist/config.js
src/require.config.js

debug non mimified vendor dependencies

---

src/tb/apps/page/forms/AbstractPage.form.js
src/tb/apps/page/widgets/InformationPage.js

I have change state of page into page status and I have add a transalation 
issue #355

change state of page in page status + translate

---

src/tb/apps/bundle/templates/index.twig

Remove unused button

---

src/tb/apps/bundle/main.js

The extensions list popin is closed automatically on changing application

Close extensions list on tab change

---

src/tb/apps/main/main.js

Use the default url from config

[Main] + use a default url

---

src/tb/apps/page/views/page.view.tree.js

Currently, the tree show just a root not a children.

[Page] + load children of the root in tree as default

---

src/tb/apps/user/templates/group/list.item.twig
src/tb/i18n/en_US/global.json

Add the translation into the catalog and correct the typo.
in relation with the issue #401

Add write_and_access translate

---

src/tb/component/treeview/templates/popin.twig

add class hidden on "show folder" functionality 
backbee/backbee-standard#53

hiding show folder functionality

---

src/tb/apps/user/controllers/group.controller.js
src/tb/apps/user/controllers/user.controller.js

Quick fix to wait the the issue backbee/core-js#9 was closed.

fix some loading issue in user app

---

src/tb/component/linkselector/main.js
src/tb/component/linkselector/templates/page-item.twig

The actual system can suggest that the link selector is not working => #397 
On this proposal i request all the page and set has disable the pages how are not online to ease the visualization.

[proposal] update link selector

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/revisionselector/templates/tree.twig
src/tb/i18n/en_US/global.json

Removing the 3 arrow from the template and add some translations.
Issue related #177 and #176

delete arrow in the 3 column

---

src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/datastore/content.datastore.js
src/tb/component/contentselector/helper/content.renderer.js
src/tb/component/contentselector/main.js
src/tb/component/contentselector/templates/searchengine.tpl
src/tb/component/datastore/DataStore.js
src/tb/component/medialibrary/main.js
src/tb/i18n/en_US/global.json

fixing popin, 
fixing search engine, 
fixing popin title

fixing contentselector issues

---

src/tb/apps/user/form/new.user.form.js
src/tb/i18n/en_US/global.json

ping @ndufreche can you merge and deploy ?
ping @clementbonfils => is it the expected behavior ?

Closes #129 - added explicit constraint message on user creation form

---

src/tb/apps/bundle/templates/confirm.twig
src/tb/apps/bundle/views/confirm.view.js

little fix to the exception raised during the popin confirmation rendering.

fix popin rendering exception

---

src/tb/apps/content/widgets/DialogContentsList.js

I use css method because position option is not enough precise.

Add block display on middle left position

---

src/tb/apps/bundle/controllers/main.controller.js

Just an forgotten action on popin validation

Close popin on validation

---

src/tb/apps/content/widgets/Edition.js
src/tb/component/medialibrary/main.js
src/tb/i18n/en_US/global.json

title field is mandantory now in media Form

title field is mandantory now in media Form

---

src/tb/component/contentselector/control/searchengine.control.js

Fixing the contentselector search engine

Fixing the contentselector search engine

---

src/tb/apps/page/views/page.view.tree.js
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/views/toolbar.view.js
src/tb/apps/user/views/user/delete.view.js
src/tb/apps/user/views/user/form.view.js

Now we can't have multiple form user creation or edition.
this closes https://github.com/backbee/backbee-standard/issues/139

Closed #139 - duplicate popin on user creation/edition

---

src/tb/apps/page/widgets/InformationPage.js
src/tb/apps/page/widgets/templates/information-page.twig

see backbee/backbee-standard#98
Add class on page status at choice "page-online" or "page-offline".
Using moment to format the page modified date and add span tag with "page-date" class to re-skin it.

Update page's info plugin

---

src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/main/controllers/main.controller.js
src/tb/apps/main/main.js
src/tb/apps/page/controllers/main.controller.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/backbee-standard/issues/90

Add popin when saving content

---

src/tb/apps/user/templates/group/list.item.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Typo correction and hiding unusable button in group

---

src/tb/apps/content/controllers/main.controller.js

Reload page after cancel content

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js

* activate the ContentSelector using the global button.
* only for viewing/deleting purposes, contents can't be drag & dropped.

Closes #426 - Activate Content selector button

---

src/tb/apps/page/templates/elements/scheduling-input.twig
src/tb/apps/page/views/page.view.contribution.index.js

See https://github.com/backbee/BbCoreJs/issues/432

Close #432 - publishing/archiving behavior is too strict

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/revisionselector/main.js
src/tb/component/revisionselector/templates/tree.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Add popin for validate or cancel content

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/main/main.js

Currenlty a popin is display after edition or dnd a picture. I had a flag on service for don't show popin on this case.

Don't confirm saving on edition of content

---

src/tb/apps/bundle/templates/index.twig

Hidding enable and disable bundle button

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/models/AbstractContent.js

https://github.com/backbee/backbee-standard/issues/133

Fix dnd of image (refreshing)

---

l stats
src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/plugins/imagepicker/main.js
src/tb/apps/contribution/templates/index.twig
src/tb/component/medialibrary/main.js
src/tb/component/medialibrary/templates/layout.tpl
src/tb/component/revisionselector/managers/Save.js
src/tb/i18n/en_US/global.json

New image picker plugin
imagepicker:
accept: ['*']
config: []

New image picker plugin

---

src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/i18n/en_US/global.json

Hide some options in page application, but also in the page tree view.
refs: https://github.com/backbee/BbCoreJs/issues/439

Hide some options if page is root

---

src/tb/apps/page/views/page.view.tree.js

https://github.com/backbee/BbCoreJs/issues/437

Fix Pages of the tree disapear

---

src/tb/apps/user/views/user/delete.view.js

debug delete view

---

src/tb/component/authentication/main.js
src/tb/i18n/en_US/global.json

* Added Log in title for the popin
* Added windows reloading to be able to call again the login form after closed it
* Add ``@todo`` for the form translation (out of scope)

REFS #463 - login form display and behavior

---

src/tb/apps/content/components/dnd/CommonDnD.js

When you drag enter now I add the class. For some visual effect that's ticket need some integration.

add class on over dropzone

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/widgets/InformationPage.js

update information page on page update

---

src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/plugins/remove/main.js

https://github.com/backbee/BbCoreJs/issues/448

[Content] [Plugins] [Remove] don't show if the parent is not a contentset

---

less/bb-ui.less
less/bb-var.less

less upgrade for manage group's rights

acl integration

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/plugins/parameters/main.js
src/tb/apps/content/widgets/DialogContentsList.js
src/tb/apps/content/widgets/Edition.js
src/tb/apps/contribution/main.js
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/main.js
src/tb/apps/page/views/page.view.clone.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.delete.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/contentselector/main.js
src/tb/component/medialibrary/main.js
src/tb/component/pagination/main.js

see #477 
popins list:
There is a little upgrade on "Page info popin" to ensure is opening only in contribution tab and a little debug into component pagination.

Add automatic close on crontribution application popins

---

src/tb/apps/content/repository/revision.repository.js

Currently, the content is validated by one request and that is a problem when there is a lot of content to validate

Use multiple request for validate contents

---

src/tb/apps/main/controllers/main.controller.js

Currently, the save doesn't work from content tab

Fix save from content tab

---

src/tb/apps/page/views/page.view.contribution.index.js

remove init date to 1970 in pub/arch page

---

src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/formbuilder/form/element/views/form.element.view.file.js

https://github.com/backbee/BbCoreJs/issues/491

Update upload processing in edition

---

src/tb/apps/content/widgets/Edition.js
src/tb/component/formbuilder/form/element/templates/textarea.twig

https://github.com/backbee/BbCoreJs/issues/494

#494 Data is all the time saved on content edition for textarea

---

src/tb/apps/main/main.js

#496 Fix to add dropzone after reload on block scope

---

src/tb/apps/content/components/PluginManager.js
src/tb/apps/content/plugins/dnd/main.js
src/tb/apps/main/main.js

see #424 
I have add too an automatic refocus on selected content.

add plugins available by default in block and content

---

src/tb/component/formbuilder/form/element/views/form.element.view.file.js

Currently, the first drag and drop doesn't work...

Fix Drag an drop as first on content edition

---

src/tb/apps/content/templates/block-display.twig

Currently the block don't have description...

Add description in panel of block

---

src/tb/apps/content/templates/contribution.index.twig
src/tb/apps/page/templates/contribution.index.twig

https://github.com/backbee/BbCoreJs/issues/501

[Contribution] #501 Hide display / display external / Display link

---

src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/components/PluginManager.js
src/tb/component/exceptions-viewer/main.js
src/tb/component/exceptions-viewer/viewer.js
src/tb/component/medialibrary/templates/media.editmode.tpl
src/tb/component/medialibrary/templates/media.viewmode.tpl

Fix buttons positions for plugins.
To change their (buttons) order we need to change the plugins order in plugins.xml

Fixing buttons position for plugins

---

src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/elements/ContentSet.js
src/tb/component/contentformbuilder/elements/Image.js
src/tb/component/formbuilder/form/element/views/form.element.view.file.js

https://github.com/backbee/BbCoreJs/issues/508
+ Fix data recovery

Add removing file on content edit and fix data recovery

---

src/tb/apps/main/main.js
src/tb/init.js

https://github.com/backbee/BbCoreJs/issues/502

#502 Fix reload after login

---

src/tb/apps/content/components/SaveManager.js

Fix save of content cause of merge revision problem

---

src/tb/apps/content/main.js
src/tb/apps/content/templates/block-description.twig
src/tb/apps/content/templates/carousel-blocks.twig
src/tb/apps/content/views/content.view.contribution.index.js

https://github.com/backbee/backbee-standard/issues/127

Add description in carousel of blocks

---

src/tb/apps/content/controllers/main.controller.js
src/tb/i18n/en_US/global.json

Result =>
When there nothing to save:
When content is save:
After content validation success:

[proposal] replacing popin by notification and success notifications

---

src/tb/component/dataview/main.js
src/tb/component/medialibrary/main.js
src/tb/component/medialibrary/templates/media.editmode.tpl
src/tb/component/medialibrary/templates/media.viewmode.tpl

fixing "select and close" medialibrary action

fixing "select and close" medialibrary action

---

src/tb/apps/content/components/MouseEventManager.js

#519 Fix use of plugins

---

src/tb/apps/main/templates/toolbar.twig

#478 Logo is missing on level 3 of page

---

src/tb/apps/content/models/ContentSet.js

#514 Add loader when a content is dropped

---

src/tb/component/linkselector/main.js

Fixing layout size for links selector

fixing layout size for links selector

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/revisionselector/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

#523 Change name of popin validation

---

src/tb/apps/content/controllers/main.controller.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

[Content] + Fix confirmation message of validation and cancelation

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/contribution/templates/index.twig
src/tb/component/revisionselector/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Save content before validate or cancel

---

src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/ElementInterpreter.js
src/tb/component/contentformbuilder/elements/Scalar.js

Add scalar on content edition

---

src/tb/component/cke/main.js
src/tb/component/contextmenu/main.js

fixing  - Contextmemu
- Fixing cke error when content is not editable
- Fixing save cke content

fixing contextmemu

---

src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/BbCoreJs/issues/551

Rename Remove to Delete in Tree page + Translation

---

src/tb/apps/content/plugins/parameters/main.js
src/tb/apps/content/widgets/Edition.js
src/tb/apps/main/main.js
src/tb/apps/page/views/page.view.clone.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.delete.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js

https://github.com/backbee/BbCoreJs/issues/571

Change position of edition popin to top

---

src/tb/component/medialibrary/main.js
src/tb/component/medialibrary/templates/media.viewmode.tpl
src/tb/component/searchengine/templates/layout.tpl
src/tb/i18n/en_US/global.json

- Fixing media creation
- Fixing mediaFolder reload
- Fixing autoload
- Enabling edit in viewmode

Fixing media creation

---

src/tb/component/formbuilder/form/element/views/form.element.view.file.js

This requests don't have API headers and do a permission denied.

Add API headers in upload request

---

src/tb/component/contentselector/main.js

show all categories by default in content selector

show all categories by default in content selector

---

src/tb/apps/page/repository/page.repository.js
src/tb/component/contentselector/helper/content.renderer.js
src/tb/component/contentselector/main.js
src/tb/component/formbuilder/form/element/views/form.element.view.file.js
src/tb/component/medialibrary/helpers/mediaitemrenderer.helper.js
src/tb/component/medialibrary/main.js
src/tb/i18n/en_US/global.json

new findContents methods  added in PageRepository
- removing ajax call on contentselector
- removing ajax call in medialibrary 
fixing jshint error from previous merge ( form.element.view.file.js )

removing ajax from contentselector and medialibrary

---

src/tb/component/formbuilder/form/element/views/form.element.view.file.js

Quick debug broken spec and jslint

debug specs

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/user/controllers/main.controller.js

See #543 only change the translation keys.

Fixed #543 - change titles of sections

---

src/tb/apps/contribution/templates/index.twig

See #594 this is only a CSS class change.
/c  @ndufreche can you merge it ?

Changed icon for  button

---

src/tb/apps/page/views/page.view.clone.js
src/tb/i18n/en_US/global.json

Add requirement to change title on page duplication

---

src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/main.js
src/tb/component/contextmenu/main.js
src/tb/component/medialibrary/main.js
src/tb/component/treeview/NodeEditor.js

Fixing autoload in medialibrary and contentselector

Fixing autoload in medialibrary and contentselector

---

src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/templates/user/list.item.twig
src/tb/apps/user/views/user/view.list.js

I have remove status switch button to the current user
see #641

Removing the to change status on current user

---

Gruntfile.js
specs/tb/component/authentication/Authentication.spec.js
src/tb/component/session/session.js

remove reloading on 403 and switch to localStorage

---

src/tb/apps/user/controllers/user.controller.js

reload groups before deleting a user

---

src/tb/apps/main/main.js
src/tb/component/authentication/main.js
src/tb/init.js

Fix reload after login

---

src/tb/apps/user/templates/user/list.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

This is enough explicit, this doesn't need more explanations /c @ndufreche

REFS #709 - Added a message when search on users dont return any results

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/views/page.view.new.js

Now, if you click again on "New page" button, the form won't be duplicated

REFS #664 - Ensure new page popin can't be duplicated

---

src/tb/apps/user/controllers/group.controller.js
src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/form/current.user.form.js
src/tb/apps/user/form/edit.user.form.js
src/tb/apps/user/form/group.form.js
src/tb/apps/user/form/new.user.form.js
src/tb/apps/user/views/group/form.view.js
src/tb/i18n/en_US/global.json

see #694, #692, #734, #749, #675

Multiple issue fix on user management application

---

src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/component/searchengine/main.js

REFS #493 
* The minimal date you can set in datetimepicker is "Now".

Dates can't be set in past

---

src/tb/apps/page/widgets/templates/information-page.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

REFS #590 
Also, notice we need to merge https://github.com/backbee/BackBee/pull/418 in same time.

Improve displaying of page statuses

---

src/tb/component/datastore/DataStore.js
src/tb/component/medialibrary/datastore/media.datastore.js
src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/component/medialibrary/main.js
src/tb/component/searchengine/main.js

fixing medialibrary search engine

fixing medialibrary search engine

---

src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/datastore/content.datastore.js
src/tb/component/contentselector/main.js
src/tb/component/searchengine/main.js

fixing search engine for content

fixing search engine for content

---

src/tb/apps/content/components/dnd/ContentDrop.js

https://github.com/backbee/BbCoreJs/issues/624

Add save confirmation when an image are dropped

---

src/tb/apps/content/plugins/remove/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/BbCoreJs/issues/778

Replace native confirm popin by an backbee popin for delete a content

---

.htaccess-old

Remove useless file .htaccess-old

---

src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

@ndufreche the BbCoreJs build sound broken on test poppin creation :/ not related to this pr.
```
PopInManager specs
- Test creation of a pop-in...>> Error: require: 'null' is not an object (evaluating 'wrapper.appendChild') at
>> _SpecRunner.html:36 
>> .grunt/grunt-contrib-jasmine/require.js:12 v
>> .grunt/grunt-contrib-jasmine/require.js:19 
>> .grunt/grunt-contrib-jasmine/require.js:23 
>> .grunt/grunt-contrib-jasmine/require.js:17 
>> .grunt/grunt-contrib-jasmine/require.js:26 
```

Fixed #776 and #777 (fixed translations)

---

src/tb/component/contentselector/helper/content.renderer.js

fixing orphaned infos when a content is deleted

Fixing orphaned infos when a content is deleted

---

src/tb/apps/content/views/content.view.contribution.index.js

REFS https://github.com/backbee/BbCoreJs/issues/781
the popin is now unique.

Now the description block popin is unique

---

src/tb/apps/user/templates/toolbar.twig

Change user search picto

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/dnd/ContentDrop.js

see #622 and theoretically the #626 
I have correct the add img wrap and add an remove wrap on DnD is ended

Debug issue happen when we add a new block image

---

src/tb/i18n/en_US/global.json

https://github.com/backbee/BbCoreJs/issues/778

Fix translate for content deletion

---

src/tb/apps/user/controllers/group.controller.js
src/tb/i18n/en_US/global.json

Add placeholder in case there is not group description

---

src/tb/apps/user/views/popin.view.js

All is in the title :)
but => :cat:

debug automated resize user popin

---

src/tb/component/authentication/main.js
src/tb/component/session/session.js

debug login after php loose session

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/components/dnd/ContentDrop.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/ContentSet.js

https://github.com/backbee/BbCoreJs/issues/809

Fix dnd of media

---

src/tb/apps/user/templates/popin.twig

removing loading message in user popin

---

src/tb/apps/user/controllers/user.controller.js

avoid bug on empty server error response

---

src/tb/apps/content/views/content.view.contribution.index.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/BbCoreJs/issues/781

Fix click of content description

---

src/tb/apps/contribution/templates/index.twig

Hidding button to watch content selector

---

src/tb/apps/contribution/templates/index.twig

Correction contents to content

---

src/tb/apps/content/plugins/contentselector/main.js
src/tb/component/cke/main.js
src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/main.js
src/tb/component/contentselector/templates/content.list.edit.view.tpl
src/tb/component/contentselector/templates/content.list.view.tpl
src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/component/medialibrary/main.js
src/tb/component/medialibrary/templates/media.editmode.tpl
src/tb/component/medialibrary/templates/media.viewmode.tpl

fixing content search engine

---

src/tb/component/contentselector/main.js
src/tb/i18n/en_US/global.json

https://github.com/backbee/BbCoreJs/issues/838

Change title of content selector

---

src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/component/medialibrary/main.js

Fixing cut & paste in media library

Fixing cut & paste in media library

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/main.js
src/tb/apps/page/templates/page.delete.twig
src/tb/apps/page/views/page.view.delete.js
src/tb/i18n/en_US/global.json

Update page deletion popin

---

src/tb/component/contentselector/templates/content.delete.tpl
src/tb/component/medialibrary/templates/media.deletemode.tpl
src/tb/i18n/en_US/global.json

fixing i18n in contentselector

fixing i18n in contentselector

---

src/tb/apps/page/widgets/InformationPage.js

https://github.com/backbee/BbCoreJs/issues/853

Change position of Information page popin

---

src/tb/apps/user/controllers/user.controller.js
src/tb/i18n/en_US/global.json

Add tooltip before user creation

---

README.md

Correct typo actual into current

---

src/tb/apps/page/widgets/InformationPage.js

On update page page check if popin exist

---

src/tb/apps/content/templates/block-description.twig

https://github.com/backbee/BbCoreJs/issues/849

Disable click and drag and drop for description block

---

src/tb/apps/page/templates/elements/scheduling-input.twig
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/i18n/en_US/global.json

https://github.com/backbee/BbCoreJs/issues/860

Fix datetimepicker for scheduling

---

src/tb/component/revisionselector/managers/Draft.js
src/tb/component/revisionselector/managers/Save.js
src/tb/component/revisionselector/templates/item-wrapper.twig

Remove useless information for basic element of backbee

Update management of revision selector

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/revisionselector/main.js
src/tb/component/revisionselector/managers/Draft.js
src/tb/component/revisionselector/templates/tree.twig
src/tb/i18n/en_US/global.json

https://github.com/backbee/backbee-standard/issues/187

Remove children if the parent is new in revision selector

---

src/tb/apps/content/controllers/main.controller.js
src/tb/i18n/en_US/global.json

Fix typo in validation popin

---

src/tb/component/formbuilder/form/views/form.view.js

Currently the serializeArray function don't retrieve data if checkbox is unchecked

Fix retrieve checkbox data from form serializeArray

---

src/tb/component/contentselector/helper/node.formater.js

apply filter when showing contentSelector categories and classcontents.

apply filter when showing contentSelector categories and classcontents

---

src/tb/apps/content/plugins/imagepicker/main.js
src/tb/component/dataview/main.js
src/tb/component/medialibrary/main.js

Allow dataview component to disable selection

Allow dataview component to disable selection

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/cke/main.js

Fixing cke editor after using the edit plugin

Fixing cke editor after using the edit plugin

---

src/tb/apps/user/templates/user/toolbar.twig
src/tb/apps/user/views/user/toolbar.js

see => backbee/backbee-standard#244

debugging user dropdown in toolbar not working

---

src/tb/apps/content/plugins/parameters/main.js

https://github.com/backbee/backbee-standard/issues/252

Fix show multiple param popin

---

src/tb/apps/main/templates/toolbar.twig

Apply dropdown system only if menu items as submenu.
see => backbee/backbee-standard#270

Update toolbar nav system

---

src/tb/component/dataview/main.js
src/tb/component/medialibrary/main.js

fixing dataview selection

---

src/tb/apps/content/templates/block-display.twig

https://github.com/backbee/backbee-standard/issues/242

Fix display content block

---

src/tb/apps/page/views/page.view.tree.js
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js

https://github.com/backbee/backbee-standard/issues/263

Fix binding of events in nodeSelector element

---

src/tb/apps/content/plugins/parameters/main.js

Currently, the content is refresh two times when submit parameters

Dont refresh two times on parameters submit

---

src/tb/apps/content/components/ContentManager.js

https://github.com/backbee/backbee-standard/issues/260

Fix refreshing of picture after render

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/models/AbstractContent.js

https://github.com/backbee/backbee-standard/issues/264

Add default zone after change parameters

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/widgets/Breadcrumb.js
src/tb/apps/contribution/controllers/main.controller.js

- https://github.com/backbee/backbee-standard/issues/278
- https://github.com/backbee/backbee-standard/issues/259

Disable select content on scope page

---

src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/models/ContentSet.js
src/tb/i18n/en_US/global.json

https://github.com/backbee/backbee-standard/issues/289

Dont select current content

---

src/tb/component/formbuilder/form/element/templates/linkSelector.twig
src/tb/component/formbuilder/form/element/templates/linkSelector_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.linkSelector.js
src/tb/component/formsubmitter/elements/linkSelector.js

https://github.com/backbee/backbee-standard/issues/274

Add edit for linkselector

---

src/tb/component/formbuilder/form/element/templates/datetimepicker.twig
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/component/formsubmitter/elements/datetimepicker.js

Currently the file for validation does'nt exist and throw an error

Add validation for datetimepicker from parameters

---

src/tb/apps/page/views/page.view.new.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

This contribution aims to fix https://github.com/backbee/backbee-standard/issues/307
ping @clementbonfils

Fixed backbee/backbee-standard#307

---

src/tb/component/revisionselector/managers/Draft.js

Quick fix for backbee/backbee-standard#297

[RevisionSelector] Fix ContentSet revision validation

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/templates/admin.twig
src/tb/apps/bundle/templates/index.twig
src/tb/apps/bundle/views/admin.view.js
src/tb/apps/bundle/views/bundle.view.index.js

Bundle administration implementation.

[RFR][bundle]Creating bundle administration system

---

src/tb/apps/page/controllers/main.controller.js

Page controller service optimisation to download less files on toolbar initialization by using more the asynchronous service system.

[page] main controller service optimisation

---

src/tb/component/contentselector/datastore/content.datastore.js
src/tb/component/contentselector/main.js
src/tb/component/contentselector/templates/layout.tpl
src/tb/component/siteselector/main.js
src/tb/component/siteselector/selector.twig
src/tb/i18n/en_US/global.json

Applying a site selector to the content selector

Applying a site selector to the content selector

---

src/tb/i18n/en_US/global.json

Fixing site selection label

---

src/tb/apps/page/views/page.view.new.js

REFS https://github.com/backbee/backbee-standard/issues/373

Fixed condition on page creation

---

src/tb/i18n/en_US/global.json

"See my plugins" instead of "See my extensions" REFS  https://github.com/backbee/backbee-standard/issues/369

Wording issue

---

src/tb/apps/bundle/controllers/main.controller.js

I have set the current view into Core container `currentAdminView`.

[bundle] easy retrieve adminView

---

src/tb/apps/user/templates/toolbar.twig

REFS https://github.com/backbee/backbee-standard/issues/366
Before:
After:

Fixed search button alignement on user section

---

src/tb/apps/bundle/views/admin.view.js

light fix to accept array in bundle admin forms.

Update admin form to accept XHTML-form format

---

src/tb/component/authentication/main.js

related to https://github.com/backbee/backbee-standard/issues/385

Sign in instead of Connexion

---

src/tb/component/contentselector/main.js

handle siteChange event in contentSelector component

handle siteChange event in contentSelector component

---

src/tb/component/linkselector/main.js
src/tb/component/linkselector/templates/layout.twig

adding siteSelector to linkSelector component

adding siteSelector to linkSelector component

---

less/bb-ui.less
less/fix.less
less/keywordselector.less
src/tb/component/autocomplete/main.js
src/tb/component/datastore/DataStore.js
src/tb/component/formbuilder/form/element/KeywordSelector.js
src/tb/component/formbuilder/form/element/templates/keywordSelector.twig
src/tb/component/formbuilder/form/element/views/form.element.view.keywordSelector.js
src/tb/component/formsubmitter/elements/keywordSelector.js
src/tb/component/keywordselector/datasource/keyword.datasource.js
src/tb/component/keywordselector/main.js

new keyword field for formbuilder

new keyword field for formbuilder

---

src/tb/component/linkselector/main.js

Fixing link selector

---

src/tb/component/formsubmitter/elements/datetimepicker.js

Currently, if we want delete the date, we can't

[Component] [Formsubmiter] Update treatment for datetimepicker

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/apps/page/views/page.view.tree.js

This method allows the page tree to show the current loaded page.

new selectPage method added to page.view.tree

---

src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.edit.js

fixing page edit form

---

src/tb/apps/bundle/views/bundle.view.list.js

https://github.com/backbee/backbee-standard/issues/407

[Bundle] Close plugins list after plugin selection

---

src/tb/component/revisionpageselector/templates/item.twig
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

added  translation key

---

src/tb/component/formbuilder/form/element/templates/nodeSelector.twig
src/tb/component/formbuilder/form/element/templates/nodeSelector_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js
src/tb/component/formsubmitter/elements/nodeSelector.js

Now we can add several node in node selector

[FormBuilder] Allow to add multiple nodes in node selector

---

src/tb/apps/page/views/page.view.manage.js

[Page manager] Auto resize backbee/backbee-standard#418

Add auto resize on page management popin

---

src/tb/component/formbuilder/form/element/views/form.element.view.linkSelector.js
src/tb/component/formbuilder/form/element/views/form.element.view.mediaSelector.js
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js

max_entry param is now available
https://github.com/backbee/docs/pull/42

[FormBuilder] Add max entry for listing element

---

src/tb/apps/page/forms/AbstractPage.form.js
src/tb/apps/page/forms/Page.form.js

https://github.com/backbee/backbee-standard/issues/361

[Page] Fix computing of new page form

---

src/tb/component/formbuilder/form/element/Url.js
src/tb/component/formbuilder/form/element/templates/url.twig
src/tb/component/formbuilder/form/element/views/form.element.view.url.js
src/tb/component/formsubmitter/elements/url.js

This introduce a new input type for formbuilder (and btw formsubmitter).
The need is when we have to make special actions on input with url or external links, we can't realy determine that with a simple text input.

introduced-url-form-type

---

src/tb/component/popin/main.js

Fixing zindex issue in "subpopin" in chrome

Fixing zindex issue in "subpopin" in chrome

---

src/tb/component/autocomplete/main.js
src/tb/component/autocomplete/templates/layout.html
src/tb/component/formbuilder/form/element/views/form.element.view.keywordSelector.js

removing subscribeOnce call in keywordSelector element

removing subscribeOnce call in keywordSelector element

---

src/tb/component/linkselector/main.js

ping @fkroockmann 
I have a question for backbee standard: if I change the type from url to link selector, do I need to update the database dump ?

Improved link selector

---

src/tb/apps/content/repository/content.repository.js

Add the current page to the request for get the new html render

[Content] Add current page on get action as html for classcontent

---

src/tb/apps/page/views/page.view.tree.js

fixing page limit in page tree.  Defaut is 25.

fixing page limit in page.view.tree

---

src/tb/apps/content/repository/content.repository.js

Send page uid instead of page in get html action

[Content] Send page uid instead of page in get html action

---

src/tb/apps/page/views/page.view.toolbar.js

https://github.com/backbee/backbee-standard/issues/421

[Page management] Fix filters

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/views/admin.view.js

https://github.com/backbee/backbee-standard/issues/424

[bundle] Fix multiple click on manage button

---

src/tb/apps/main/templates/toolbar.twig
src/tb/apps/main/views/main.view.index.js
src/tb/i18n/en_US/global.json

https://github.com/backbee/backbee-standard/issues/421

Rename page to page management in menu

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/treeview/PopinTreeView.js
src/tb/component/treeview/templates/popin.twig
src/tb/i18n/en_US/global.json

Enabling filter by section in Page tree

Enabling filter by section in Page tree

---

src/tb/apps/page/views/page.view.tree.js

enabling drag and drop on page tree

enabling drag and drop on page tree

---

src/tb/apps/page/views/page.view.tree.js

adding height to pagetree dialog

adding height to pagetree dialog

---

src/tb/apps/page/views/page.view.tree.js

fixing limit in tree view

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/models/AbstractContent.js
src/tb/apps/content/repository/keyword.repository.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/ElementInterpreter.js
src/tb/component/contentformbuilder/elements/ContentSet.js
src/tb/component/contentformbuilder/elements/Image.js
src/tb/component/contentformbuilder/elements/Keyword.js
src/tb/component/contentformbuilder/elements/Text.js
src/tb/component/contentformbuilder/main.js

Currently, keyword element is not editable

Add form for keyword as element

---

src/tb/apps/page/forms/AbstractPage.form.js
src/tb/apps/page/forms/Page.form.js

[Page] Add name for page form

---

src/tb/component/formbuilder/main.js

[Component] Add preRender event for form

---

package.json

Add es5-shim

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/views/page.view.manage.js

https://github.com/backbee/backbee-standard/issues/441

Refresh tree after change in page management

---

src/tb/apps/page/controllers/main.controller.js

Jslint was not checked cause of bug with esm in travis

Fix jslint

---

src/tb/component/cke/main.js

https://github.com/backbee/backbee-standard/issues/446

Fix saving after edit text with cke

---

src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/contribution/templates/index.twig
src/tb/apps/contribution/views/contribution.view.index.js
src/tb/component/datastore/DataStore.js
src/tb/component/keywordseditor/datastore/keyword.datastore.js
src/tb/component/keywordseditor/helper/contextmenu.helper.js
src/tb/component/keywordseditor/main.js
src/tb/component/medialibrary/main.js
src/tb/component/treeview/NodeEditor.js
src/tb/component/treeview/PopinTreeView.js
src/tb/component/treeview/TreeView.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

new keywords editor

---

specs/tb/component/logger/Logger.spec.js
src/tb/component/notify/main.js

Reset log before test logger
Return when using javascript selector

Fix jasmine test

---

src/tb/apps/page/widgets/InformationPage.js
src/tb/apps/page/widgets/templates/information-page.twig

https://github.com/backbee/backbee-standard/issues/448

Add prerender event for information page

---

src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/components/MouseEventManager.js
src/tb/apps/content/components/PluginManager.js
src/tb/apps/content/plugins/contentplugin.js

context menu for content

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/forms/AbstractPage.form.js
src/tb/apps/page/forms/Page.form.js
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js
src/tb/component/formbuilder/form/element/views/form.element.view.checkbox.js
src/tb/component/formbuilder/form/element/views/form.element.view.hidden.js
src/tb/component/formbuilder/form/element/views/form.element.view.password.js
src/tb/component/formbuilder/form/element/views/form.element.view.radio.js
src/tb/component/formbuilder/form/element/views/form.element.view.select.js
src/tb/component/formbuilder/form/element/views/form.element.view.text.js
src/tb/component/formbuilder/form/element/views/form.element.view.textarea.js
src/tb/component/formbuilder/form/element/views/form.element.view.url.js

- Now, we can choose the parent on creation and editing page
- Fix .toString method in form, use String class instead cause we can't transform string of null

Allow to choose parent on edit/creation of page in toolbar only

---

src/tb/apps/page/views/page.view.manage.js

https://github.com/backbee/backbee-standard/issues/449

[Page management] Reset select action after use this

---

bower.json

Update corejs version to 0.1.*

Update corejs version

---

src/tb/apps/content/plugins/imagepicker/main.js

https://github.com/backbee/backbee-standard/issues/465

Fix imagepicker translation

---

src/tb/component/formbuilder/form/element/templates/contentSet_item.twig
src/tb/component/formbuilder/form/element/templates/mediaSelector_item.twig

I remove "Christian" that was written and add item properties instead.

Fix christian in toolbar

---

src/tb/component/revisionselector/templates/item-wrapper.twig
src/tb/component/revisionselector/templates/tree.twig

https://github.com/backbee/backbee-standard/issues/461

Remove author in revision selector

---

less/fix.less
src/tb/apps/content/components/ContentActionWidget.js
src/tb/apps/content/plugins/dnd/main.js
src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/contentselector/main.js
src/tb/component/formbuilder/form/element/templates/nodeSelector_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js
src/tb/component/linkselector/main.js
src/tb/component/siteselector/main.js
src/tb/component/treeview/PopinTreeView.js
src/tb/component/treeview/templates/popin.twig

Enabling site selector in PageTree

Enabling site selector in PageTree

---

src/tb/apps/content/models/AbstractContent.js

https://github.com/backbee/backbee-standard/issues/443

Fix rendermode when update content

---

src/tb/apps/page/repository/page.repository.js
src/tb/apps/page/views/page.view.tree.js

Fixing page tree when current page can't be found

Fixing page tree when current page can't be found

---

src/tb/component/keywordseditor/main.js

Fixing kweditor

---

src/tb/apps/page/views/page.view.new.js

https://github.com/backbee/backbee-standard/issues/475

Fix limit of title length in page creation

---

src/tb/apps/page/views/page.view.tree.js

https://github.com/backbee/backbee-standard/issues/473

Fix popin page title

---

src/tb/apps/content/widgets/Breadcrumb.js

https://github.com/backbee/backbee-standard/issues/471

Fix breadcrumb click

---

dist/config.js
src/tb/init.js

Hook are used in project for override several popin or other...

Add hook management

---

src/tb/apps/page/views/page.view.tree.js
src/tb/component/formbuilder/form/element/views/form.element.view.nodeSelector.js

Auto open Page tree

---

src/tb/apps/page/views/page.view.tree.js

Currently, the mask is on a bad context

Fix mask context in page tree

---

src/tb/apps/content/components/ContentManager.js
src/tb/component/contentformbuilder/ElementInterpreter.js
src/tb/component/contentformbuilder/elements/File.js

Saw with @crouillon, can be merged for now
missing features:
- display size of pdf files
- display pdf in media library

[RFR] - be able to deal with PDF files in contentManager

---

src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js

Fix top for datetimepicker input

---

src/tb/apps/content/components/dnd/ContentDrop.js

https://github.com/backbee/backbee-standard/issues/477

Fix image dnd

---

src/tb/apps/page/views/page.view.edit.js

https://github.com/backbee/backbee-standard/issues/475

Add title validation for page edit

---

src/tb/apps/bundle/views/admin.view.js

remove 20pixel from total width to view scrollbar and exit button

[CORE] remove 20pixel from total width to view scrollbar and exit button

---

src/tb/component/contentformbuilder/elements/File.js

https://github.com/backbee/backbee-standard/issues/486

Fix empty value for file element in form

---

src/tb/component/popin/main.js

make the popin scrollable instead of body background

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/content/widgets/Edition.js

Currently for each element a request are send.

Optimize content form edition

---

src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js

Currently the datetimepicker is all the time in english

Add lang according to bo locale for datetimepicker

---

src/tb/apps/bundle/controllers/main.controller.js
src/tb/apps/bundle/repository/bundle.repository.js

On extension tab, only manageable must be shown.

Show only manageable bundles

---

src/tb/component/popin/main.js

fixed popins behavior

---

src/tb/apps/page/views/page.view.tree.js

fixing tree-loading

---

src/tb/apps/content/models/ContentSet.js

On drop, i check if the contentset have rendermode as param then i check the data-rendermode

Fix rendermode on content drop

---

src/tb/component/keywordseditor/main.js
src/tb/component/treeview/NodeEditor.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

fixing node editor

---

src/tb/apps/user/controllers/user.controller.js

https://github.com/backbee/backbee-standard/issues/492

Catch internal error from REST in user application

---

src/tb/component/contentformbuilder/elements/File.js
src/tb/component/formbuilder/form/element/views/form.element.view.file.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/backbee-standard/issues/489

Add accepted file management + fix details from upload

---

src/tb/component/medialibrary/helpers/contextmenu.helper.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Fix traduction for media creation

---

src/tb/apps/bundle/templates/index.twig

I change class to have a best view on extension.

[twig] add width and change class to have good view for extension thumb

---

src/tb/component/contextmenu/main.js
src/tb/component/datastore/DataStore.js
src/tb/component/keywordseditor/datastore/keyword.datastore.js
src/tb/component/keywordseditor/helper/contextmenu.helper.js
src/tb/component/keywordseditor/main.js
src/tb/component/treeview/NodeEditor.js
src/tb/component/treeview/TreeView.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

adding pagination to kw editor

Adding pagination to kw editor

---

src/tb/component/contentformbuilder/elements/File.js
src/tb/component/formbuilder/form/element/views/form.element.view.file.js

Fix upload detail when drag and drop pdf etc

Fix upload detail

---

src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/elements/All.js
src/tb/component/contentformbuilder/elements/ContentSet.js
src/tb/component/contentformbuilder/elements/File.js
src/tb/component/contentformbuilder/elements/Text.js
src/tb/component/contentformbuilder/main.js

Curently the edition is broken if an element is null

Fix edition with null element

---

src/tb/apps/content/widgets/Edition.js

Currently, we can't close a parent popin if a child popin is open

Fix popin management in content edition

---

src/tb/apps/content/widgets/Edition.js
src/tb/apps/page/controllers/main.controller.js
src/tb/component/contentformbuilder/elements/All.js
src/tb/component/contentformbuilder/elements/ContentSet.js
src/tb/component/contentformbuilder/elements/File.js
src/tb/component/contentformbuilder/elements/Keyword.js
src/tb/component/contentformbuilder/elements/Scalar.js
src/tb/component/contentformbuilder/elements/Text.js

Currently the label written in yml file is not used for edition form

Fix labelize in edition form

---

src/tb/apps/page/views/page.view.new.js

Fix move to for use in page creation

Fix move to for new page

---

src/tb/apps/page/templates/page.delete.twig
src/tb/apps/page/views/page.view.delete.js

The popin is all the time masked if the user don't have a correct rights

Fix page deletion without rights

---

src/tb/component/formbuilder/form/element/templates/content.twig
src/tb/component/formbuilder/form/element/templates/contentSet.twig
src/tb/component/formbuilder/form/element/templates/contentSet_item.twig
src/tb/component/formbuilder/form/element/templates/linkSelector.twig
src/tb/component/formbuilder/form/element/templates/linkSelector_item.twig
src/tb/component/formbuilder/form/element/templates/mediaSelector.twig
src/tb/component/formbuilder/form/element/templates/mediaSelector_item.twig
src/tb/component/formbuilder/form/element/templates/nodeSelector.twig
src/tb/component/formbuilder/form/element/templates/nodeSelector_item.twig

The default type of button is submit. So the submit event when we use enter button is catched by all button in elements.

Fix submit event used by elements

---

src/tb/component/authentication/main.js

Sometimes a login popin can't be close

Fix reload after logout

---

src/tb/apps/contribution/views/contribution.view.index.js

Prevent the page tree from loading many times

Prevent the page tree from loading many times

---

src/tb/apps/page/views/page.view.tree.js

Better loading management on pagetree

Better loading management on pagetree

---

src/tb/apps/page/views/page.view.contribution.index.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

We need to display an error message in publishing/archiving form when publication date is before today date

Prevent user from publish in the past

---

src/tb/apps/page/views/page.view.tree.js

fix siteslector event in pagetree

fixing site change in pagetree

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/repository/content.repository.js

When a 404 is throw on save, i create a new content and update a parent element

Create element if is null

---

src/tb/apps/content/components/SaveManager.js

Remove console log

---

src/tb/component/contentselector/main.js

fixing site selection in content selector

fixing site selection in content selector

---

src/tb/i18n/fr_FR/global.json

fixing fixing local

---

src/tb/component/revisionselector/templates/item-wrapper.twig

fixing draft template

---

src/tb/component/linkselector/main.js

fixing linkselector

---

src/tb/component/formbuilder/form/element/templates/select.twig
src/tb/component/formbuilder/form/element/views/form.element.view.select.js

In nunjucks we can't retrive key with a real array in for loop

Fix bug of array in select element

---

src/tb/component/linkselector/main.js

Bad context for create the form

Fix add link from the external link

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/templates/dropzone.twig

the behavior has been validated by @clementbonfils ;)

Non accepted block are non droppable

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/components/MouseEventManager.js

Enabling context menu on Element/Image

Enabling context menu on Element/Image

---

src/tb/component/cke/main.js

allowing extraplugins in cke editor

allowing extraplugins in cke editor

---

src/tb/component/linkselector/main.js
src/tb/component/linkselector/templates/page-item.twig

display dates in link selector

---

src/tb/apps/content/controllers/main.controller.js

fixing repository service

---

src/tb/component/pagination/helper/renderer.helper.js
src/tb/component/pagination/main.js

enabling singlepagemode in pagination component

enabling singlepagemode in pagination component

---

src/tb/component/dataview/main.js
src/tb/component/medialibrary/main.js

changing pagination for medialibrary

changing pagination for medialibrary

---

src/tb/component/contentselector/datastore/content.datastore.js
src/tb/component/contentselector/main.js

changing pagination mode in contentselector

changing pagination mode in contentselector

---

src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/component/menu/main.js

adding new add setButtons to menu

adding new add setButtons to menu

---

src/tb/apps/content/plugins/contentsplitter/main.js

fixing event in contentsplitter

fixing event in contentsplitter

---

src/tb/apps/page/views/page.view.edit.js

The problem is only on the 1 submit of the form. On the second submit it worked.

#500 Fix refresh page after layout edit

---

src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/apps/page/views/page.view.tree.js

#518 - Fix tree opening when no page was created

---

composer.json

Removed `Nicolas Dufreche` from authors cause there was a typo in his email and this email is not longer valid. Added @fkroockmann and @hbaptiste instead.

updated composer.json with valid informations

---

src/tb/apps/content/plugins/contentsetplus/main.js

add missing attributes (visible & thumbnail ) on object 'content'

Fix issue on contentsetplus

---

src/tb/apps/page/store/page.store.js
src/tb/apps/page/views/page.view.manage.js
src/tb/apps/page/views/page.view.toolbar.js
src/tb/i18n/en_US/global.json
src/tb/i18n/es_ES/global.json
src/tb/i18n/fr_FR/global.json

[PAGE MANAGEMENT] redefine and develop search on pages 
- new parameter added to make the difference between page list and page tree
- translation for label "No page found." are needed for this languages: chines, russian, german

#531 redefine and develop search on pages

---

src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/component/formbuilder/form/Form.js
src/tb/component/formbuilder/form/element/views/form.element.view.datetimepicker.js
src/tb/component/formbuilder/form/templates/form.twig
src/tb/component/formbuilder/main.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

- added the minutes inside the hours picker
- extended formbuilder to allow additional buttons
- publish now functionality from scheduling section

#539 Add hours and minutes to the schedulling section

---

src/tb/component/contentselector/main.js

resize panel via resizeAll() after render content in panel

update layout after render content in panels

---

src/tb/apps/page/templates/validation.twig

Remove the duplicated question mark from page management set online / offline.

[PAGE MANAGEMENT] Col filter are ko

---

src/tb/component/formsubmitter/elements/contentTypeSelector.js

contentTypeSelector send {} when it is not edited and remove current value

fix contentTypeSelector send {} when it is not edited

---

src/tb/apps/page/templates/page.delete.twig

Solves https://github.com/backbee/backbee-standard/issues/566

[TREE] Deleting a page displays a message with two ?

---

src/tb/component/contentformbuilder/elements/Keyword.js
src/tb/component/formbuilder/form/element/views/form.element.view.text.js

Edition is broken cause of keyword

Fix edition of keyword if is null

---

src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/widgets/Edition.js
src/tb/component/contentformbuilder/elements/Keyword.js

- Fix keyword edition
- if no change dont refresh parent

Fix keyword edition + optimize refresh when no change

---

src/tb/apps/user/form/new.user.form.js

https://github.com/backbee/backbee-standard/issues/559

#552 - when creating new user make first name second name compulsory

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/page/views/page.view.tree.js

In some cases the popin shouldn't be hidden on first load.

Tree adjustments refs:#5362

---

src/tb/apps/page/templates/toolbar.twig
src/tb/component/rangeselector/main.js

Solves : https://github.com/backbee/backbee-standard/issues/569
Solves also range selector and pagination issue.

[PAGE MANAGEMENT] Enable user to search page by status

---

src/tb/apps/content/templates/block-display.twig

https://github.com/backbee/backbee-standard/issues/559

#559 - drag and drop

---

src/tb/component/keywordseditor/main.js

click on the next was impossible if isEditing was true

[keywordselector] set isEditing to false if response fail

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/components/dnd/ContentDrop.js
src/tb/apps/content/widgets/Edition.js

Currently the refresh doesnt work correctly

Fix dnd of picture from desktop

---

src/tb/apps/content/plugins/remove/main.js
src/tb/component/formbuilder/form/element/views/form.element.view.contentSet.js

- Fix data send to template itemTemplate and update the list in form edit
- Save data on remove plugin

[Content Body] bad display and update of the form

---

src/tb/apps/page/views/page.view.tree.contribution.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Solves: https://github.com/backbee/backbee-standard/issues/394

[TREE] Refresh tree after manipulation and display a notification

---

src/tb/apps/page/controllers/main.controller.js

https://github.com/backbee/backbee-standard/issues/563

#563 - [MENU] accessibility

---

src/tb/apps/content/plugins/contentsplitter/main.js

There was a problem with contentsplitter main.js for grunt test

Fix contentsplitter grunt test

---

src/tb/apps/user/controllers/user.controller.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/backbee-standard/issues/565

#565 - When user is removed from a group

---

src/tb/apps/user/controllers/user.controller.js
src/tb/apps/user/entity/user.js
src/tb/apps/user/templates/user/list.item.twig
src/tb/apps/user/views/user/view.list.js

Related issue https://github.com/backbee/backbee-standard/issues/553

[USER] prevent from deleting administrator user

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/views/page.view.validation.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Related issue: https://github.com/backbee/backbee-standard/issues/572
Observation: the loader will appear when validating the deletion of pages as per discussed with Clement.

[PAGE MANAGEMENT] delete page

---

src/tb/apps/bundle/controllers/main.controller.js

Related issue: https://github.com/backbee/backbee-standard/issues/576

[PLUGINS] set loader on bundle list

---

src/tb/component/formbuilder/form/element/templates/contentTypeSelector_item.twig
src/tb/component/formbuilder/form/element/views/form.element.view.contentTypeSelector.js

Now we can add a flag "allow_disable" for non accept in content type selector

Add non accept on content type selector

---

src/tb/apps/bundle/views/admin.view.js

https://github.com/backbee/backbee-standard/issues/577

#577 - Destroy popin after closure

---

src/tb/apps/content/components/DndManager.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/plugins/contentselector/main.js
src/tb/apps/content/plugins/contentsetplus/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/568

[BLOCKS] Add a max entry on contentset

---

src/tb/apps/content/plugins/contentsplitter/main.js

removing the use of jqueryObject from the splitted content

fixing content splitter

---

src/tb/apps/page/views/page.view.tree.management.js

A parameter was not added in the ajax request.
Issue link: https://github.com/backbee/backbee-standard/issues/582

Page management switch from trash #582

---

less/ckeditor_dialog.less
src/tb/component/cke/skins/backbee/dialog.css

The width and height to 0 prevent close of popin

Fix link on cke

---

src/tb/component/revisionpageselector/main.js

Add mask for prevent click before check draft

Fix page validation popin

---

src/tb/apps/content/templates/edit-contribution.index.twig
src/tb/component/cke/main.js

Some times the editor doesnt appear

Fix cke message

---

src/tb/apps/bundle/controllers/main.controller.js

https://github.com/backbee/backbee-standard/issues/585

Close admin popin after scope changed

---

src/tb/apps/contribution/controllers/main.controller.js
src/tb/apps/main/components/ToolbarManager.js
src/tb/apps/main/views/main.view.index.js

https://github.com/backbee/backbee-standard/issues/589

Fix management of menu

---

src/tb/apps/content/components/ContentManager.js
src/tb/apps/content/plugins/contentselector/main.js
src/tb/apps/content/plugins/contentsetplus/main.js
src/tb/apps/content/widgets/DialogContentsList.js

Related issue: https://github.com/backbee/backbee-standard/issues/581

[BLOCKS] Accepts in contentset and content selector

---

.gitignore
Gruntfile.js
README.md
nightwatch.json
nightwatch/configuration/globals.json.dist
nightwatch/tests/pageLoad.js
package.json

Basic structure for nightwatch, functional testing

Nightwatch basic structure

---

src/tb/apps/content/plugins/parameters/main.js

check if content have a parent

fix plugin parameters

---

.gitignore
Gruntfile.js
nightwatch.json
nightwatch/commands/login/closeLoginPopin.js
nightwatch/commands/login/openLoginPopin.js
nightwatch/commands/utils/getLocalStorage.js
nightwatch/commands/utils/openUrl.js
nightwatch/commands/utils/windowSetClassOnElement.js
nightwatch/configuration/globals.json.dist
nightwatch/objects/login/login.js
nightwatch/tests/pageLoad.js
nightwatch/tests/user/login.js

Related issue: https://github.com/backbee/backbee-standard/issues/590

[FUNCTIONNAL TEST] Login

---

src/tb/component/pagination/main.js

When total is not a number we set it to 0 in setItems when the renderMode is SINGLE_PAGE_MODE.

fixing pagination component

---

src/tb/apps/content/widgets/Edition.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js
src/tb/apps/page/views/page.view.tree.js
src/tb/component/popin/main.js
src/tb/component/revisionpageselector/main.js
src/tb/component/revisionselector/main.js

edit page,
new page,
treeview/ tag

manage popin: add modal: true on some modal; check position before display

---

src/tb/apps/content/components/dnd/ContentDrop.js
src/tb/apps/content/controllers/main.controller.js
src/tb/apps/content/main.js
src/tb/apps/content/models/ContentSet.js
src/tb/apps/content/widgets/DialogAddToMediaLibrary.js
src/tb/apps/contribution/controllers/main.controller.js
src/tb/component/session/session.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/backbee-standard/issues/599

Add to library feature

---

src/tb/component/contentselector/main.js

https://github.com/backbee/backbee-standard/issues/597

[Content selector] select first category

---

src/tb/apps/contribution/views/contribution.view.index.js
src/tb/apps/main/main.js
src/tb/apps/page/views/page.view.tree.contribution.js

https://github.com/backbee/backbee-standard/issues/593

Fix page creation with wrong parent refs#593

---

src/tb/apps/page/views/page.view.delete.js
src/tb/apps/page/views/page.view.edit.js
src/tb/apps/page/views/page.view.new.js

In order to make proper test cases, we need some classes to be set before

Add usefull classes for nightwatch tests

---

src/tb/apps/content/widgets/DialogAddToMediaLibrary.js

Related issue: https://github.com/backbee/backbee-standard/issues/642

[MEDIA] TypeError: parentElements[key] is null

---

nightwatch.json
nightwatch/commands/login/logout.js
nightwatch/configuration/globals.json.dist
nightwatch/objects/page/popins.js
nightwatch/objects/page/tree.js
nightwatch/tests/page/tree.js

Related issue: https://github.com/backbee/backbee-standard/issues/592
Not all tests are implemented as some depend on another issues.

[PAGE SERVICE] Page Tree

---

src/tb/apps/page/views/page.view.tree.contribution.js

Fix for issue: https://github.com/backbee/backbee-standard/issues/657

offline page moved in tree #657

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/templates/manage.list.twig
src/tb/apps/page/views/page.view.manage.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

Fix for issue: https://github.com/backbee/backbee-standard/issues/658

Restoring trash page #658

---

src/tb/apps/page/views/page.view.manage.js

I've found a bug, I missed an empty space.

Fix offline option #658

---

src/tb/apps/content/components/ContentManager.js

On firefox the naturalWidth is undefined in some case

Fix refresh image on firefox

---

src/tb/component/contentselector/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/656
Fixed also nightwatch test contentClick

[CONTENT SELECTOR] Pagination is KO

---

src/tb/component/popin/main.js

in unmask function, looking for a form element, check if first element is a input and set focus on it.

focus on input in a popin

---

src/tb/apps/page/controllers/main.controller.js
src/tb/apps/page/templates/contribution.index.twig
src/tb/apps/page/views/page.view.contribution.index.js
src/tb/apps/page/views/page.view.tree.js
src/tb/apps/page/widgets/InformationPage.js
src/tb/i18n/en_US/global.json
src/tb/i18n/fr_FR/global.json

https://github.com/backbee/backbee-standard/issues/655

Fix page view for dynamic page

---

src/tb/component/contentformbuilder/elements/Text.js
src/tb/component/formbuilder/form/element/Textarea.js

On first textarea rendering, config.value is undefined

Fix textarea form build

---

src/tb/apps/content/components/MouseEventManager.js

Related issue: https://github.com/backbee/backbee-standard/issues/691

[MEDIA] display image plugins on right click over the image

---

src/tb/component/contentselector/main.js
src/tb/component/medialibrary/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/690

[CONTENT SELECTOR/MEDIA LIBRARY] Search by press enter

---

src/tb/apps/content/models/ContentSet.js

Related issue: https://github.com/backbee/backbee-standard/issues/692

[CONTENT] enable user to click the + plugin several time

---

src/tb/apps/page/views/page.view.tree.js

Related issue: https://github.com/backbee/backbee-standard/issues/693

[TREE] Closed popin do not show on refresh

---

src/tb/apps/content/widgets/DialogAddToMediaLibrary.js

Related issue https://github.com/backbee/backbee-standard/issues/694

[MEDIA] improve the automatic add of media to the library

---

src/tb/apps/content/widgets/DialogAddToMediaLibrary.js

https://github.com/backbee/backbee-standard/issues/694
Moved the checkbox below the buttons

[MEDIA] automatic add media to library move checkbox below

---

src/tb/component/datastore/DataStore.js
src/tb/component/linkselector/main.js
src/tb/component/linkselector/templates/layout.twig
src/tb/component/searchengine/main.js
src/tb/component/searchengine/templates/layout.tpl

Related issue: https://github.com/backbee/backbee-standard/issues/707

[LINK SELECTOR] search engine and page numbering are missing

---

src/tb/component/keywordseditor/main.js

https://github.com/backbee/backbee-standard/issues/695

#695 - Can't create a level 2 keyword in tree

---

src/tb/component/linkselector/main.js

[LINK SELECTOR] handler enter key on search form

---

src/tb/component/datastore/DataStore.js
src/tb/component/medialibrary/main.js

https://github.com/backbee/backbee-standard/issues/710

#710 - add next button in media library

---

src/tb/component/popin/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/700

[POPINS] Disable popins in the back

---

src/tb/apps/content/controllers/main.controller.js
src/tb/component/revisionpageselector/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/716

[PAGE] putting a page online without validating content first is KO

---

src/tb/apps/page/controllers/main.controller.js
src/tb/i18n/en_US/global.json

Related issue: https://github.com/backbee/backbee-standard/issues/726

[PAGE MANAGEMENT] ACL dont apply on the page management section

---

src/tb/component/cke/main.js

Related issue: https://github.com/backbee/backbee-standard/issues/729

[CKE] lost pf focus on CKE after adding a link

---

src/tb/apps/content/widgets/DialogContentsList.js

Related issue: https://github.com/backbee/backbee-standard/issues/736

[BLOCKS] - Blocks are not loaded

---

src/tb/apps/content/components/dnd/CommonDnD.js

Related issue: https://github.com/backbee/backbee-standard/issues/738

[DROPZONE] improve dropzones accessibility

---

dist/ckeeditor/plugins/link/dialogs/link.js

https://github.com/backbee/backbee-standard/issues/743

#743 - select 'target blank' by default

---

src/tb/component/contentselector/control/searchengine.control.js
src/tb/component/contentselector/datastore/content.datastore.js
src/tb/component/contentselector/templates/searchengine.tpl
src/tb/i18n/en_US/global.json

Related issue: https://github.com/backbee/backbee-standard/issues/742

[CONTENT SELECTOR] hide content that not are not linked to pages

---

src/tb/component/cke/main.js

fix the loading of rte configuration
Thanks @fkroockmann for your help

[RTE] fix config loading

---

src/tb/component/medialibrary/helpers/mediaitemrenderer.helper.js
src/tb/component/popin/PopIn.js

https://github.com/backbee/backbee-standard/issues/701

#701 - put the generic BackBee popin style for popin delete media

---

src/tb/component/contentformbuilder/ElementInterpreter.js
src/tb/component/contentformbuilder/elements/Date.js
src/tb/component/formsubmitter/elements/datetimepicker.js

Rendering for BackBee\ClassContent\Element\Date

Form element date

---

src/tb/apps/content/components/SaveManager.js

At first assignation of a keyword, the keyword was not related to a content

Fix keywords contents relation

---

src/tb/apps/content/components/SaveManager.js
src/tb/apps/content/repository/content.repository.js
src/tb/apps/content/repository/keyword.repository.js
src/tb/component/contentformbuilder/elements/Keyword.js

Ensure that Keywords are saved before any other contents, in order to be able to properly create the relation between them and the parent content

Save keywords before other contents

---

src/tb/component/formsubmitter/elements/datetimepicker.js

Fix the saving for elements of type "BackBee\ClassContent\Element\Date"

Fix element date saving

---

Gruntfile.js
package.json
specs/tb/component/authentication/Authentication.spec.js
src/tb/component/session/session.js

Fix headers for Chrome 60 - issue #1352

[#1352] - Fix headers for Chrome 60

---

Gruntfile.js
package.json
specs/tb/component/authentication/Authentication.spec.js
src/tb/component/session/session.js

Reverts backbee/backbee-js#1353

Revert "[#1352] - Fix headers for Chrome 60"
